### ISSUE TITLE
Failed to install 'de.appplant.cordova.plugin.background-mode':Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".

### ISSUE THREAD

**Issue by maxfriedmann** [buildhybrid/background#1]
Hi there,
I'd like to use this nice meteor version of the background-mode. Unfortunately I get an error when starting either the ios or the android emulator : 

% Adding a platform ios
Using (built-in) Android SDK at /Users/max/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'add', 'ios' ]
Error while running for mobile platforms: Error running
/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Failed to install 'de.appplant.cordova.plugin.background-mode':Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got
"cordova-plugin-device".
at checkID
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
at
/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
at _fulfilled
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at
/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:442:13)
Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
at checkID
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
at
/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
at _fulfilled
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at
/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush
(/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:442:13)

Fetching plugin "de.appplant.cordova.plugin.background-mode@0.6.3" via plugin registry
Installing "de.appplant.cordova.plugin.background-mode" for android
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone

Error: Error running /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Failed to install 'de.appplant.cordova.plugin.background-mode':Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
    at checkID (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
    at _fulfilled (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
Error: Expected fetched plugin to have ID "org.apache.cordova.device" but got "cordova-plugin-device".
    at checkID (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
    at _fulfilled (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)

Fetching plugin "de.appplant.cordova.plugin.background-mode@0.6.3" via plugin registry
Installing "de.appplant.cordova.plugin.background-mode" for android
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone

    at execFileSyncOrThrow (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at installPlugin (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:483:17)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:672:11
    at Function._.each._.forEach (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:671:11
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at ensureCordovaPlugins (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:661:18)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:797:5
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at buildCordova (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:769:16)
    at Object.cordova.buildTargets (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:137:3)
    at Command.doRunCommand [as func] (/Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:324:15)
    at /Users/max/.meteor/packages/meteor-tool/.1.1.3.1fc213p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
web|develop⚡ ⇒

**Comment by RedDeathAt614** [comment]
Hi! Any news on this? I'm getting the same error..
